""" Main entry point to start using SECGENLint. """
from secgenlint.main import main as secgenlint

class SECGENLint:

    def __init__(self):
        pass

    """
    Process the vulnerable report generated by SECGEN.

    Attributes:
        input_file_path: Path to the file to be analyzed.
        output_file_path: Path to the file to where the output will be written.
    """
    def run(self, input_file_path: str, output_file_path: str, show_score:bool, quiet:bool) -> None:
        secgenlint(report=input_file_path, 
                   out=output_file_path,
                   show_score=show_score,
                   quiet=quiet)
